package visao.aluno;

import controle.aluno.PagamentoDAO;
import controle.detran.CarteiraDAO;
import visao.aluno.servicos.Boleto;
import controle.detran.ServicoDAO;
import controle.aluno.AlunoDAO;
import modelo.ServicoDTO;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.AlunoDTO;
import modelo.Usuario;
import visao.Login;
import visao.aluno.servicos.InterfaceNovaCNH;

public class MainAluno extends javax.swing.JFrame {

    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    Date dataAtual = new Date();
    
    int idAlunoLogado = AlunoDTO.usuarioLogado.getId_usuario();

    /**
     * Creates new form InterfaceAluno
     */
    public MainAluno() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        permitirRenovacao();
        permitirSegundaVia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuarioLogado = new javax.swing.JLabel();
        btnSegundavia = new javax.swing.JButton();
        btnEmissao = new javax.swing.JButton();
        btnRenovacao = new javax.swing.JButton();
        txtData = new javax.swing.JLabel();
        btnFecharSistema = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtUsuarioLogado.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtUsuarioLogado.setText("Olá, #nomeAluno");

        btnSegundavia.setBackground(new java.awt.Color(0, 0, 0));
        btnSegundavia.setForeground(new java.awt.Color(255, 255, 255));
        btnSegundavia.setText("Segunda via CNH");
        btnSegundavia.setEnabled(false);
        btnSegundavia.setOpaque(false);
        btnSegundavia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSegundaviaActionPerformed(evt);
            }
        });

        btnEmissao.setBackground(new java.awt.Color(0, 0, 0));
        btnEmissao.setForeground(new java.awt.Color(255, 255, 255));
        btnEmissao.setText("Emissão de nova CNH");
        btnEmissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmissaoActionPerformed(evt);
            }
        });

        btnRenovacao.setBackground(new java.awt.Color(0, 0, 0));
        btnRenovacao.setForeground(new java.awt.Color(255, 255, 255));
        btnRenovacao.setText("Renovação CNH");
        btnRenovacao.setEnabled(false);
        btnRenovacao.setOpaque(false);
        btnRenovacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenovacaoActionPerformed(evt);
            }
        });

        txtData.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtData.setText("Data");

        btnFecharSistema.setBackground(new java.awt.Color(255, 51, 51));
        btnFecharSistema.setForeground(new java.awt.Color(255, 255, 255));
        btnFecharSistema.setText("Sair");
        btnFecharSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharSistemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnSegundavia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEmissao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRenovacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFecharSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtUsuarioLogado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsuarioLogado)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(btnEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnSegundavia, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnRenovacao, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnFecharSistema)
                .addGap(24, 24, 24))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmissaoActionPerformed
        ResultSet rsPgmDAO = new PagamentoDAO().buscar(Usuario.usuarioLogado.getId_usuario());

        try {
            if (rsPgmDAO.next()) {
                this.dispose();
                new InterfaceNovaCNH().setVisible(true);
            } else {
                buscarServico(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEmissaoActionPerformed

    private void btnRenovacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenovacaoActionPerformed
        buscarServico(3);
    }//GEN-LAST:event_btnRenovacaoActionPerformed

    private void btnSegundaviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSegundaviaActionPerformed
       AlunoDAO alunoDAO = new AlunoDAO();
        ResultSet rsCarteira = alunoDAO.verificaSeContemCarteira();
    try {
        if (rsCarteira.next()) {
            buscarServico(2);
        } else {
            JOptionPane.showMessageDialog(null, "Usuário não possui carteira.");
        }
    } catch (SQLException ex) {
        Logger.getLogger(MainAluno.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnSegundaviaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txtUsuarioLogado.setText("Olá, " + Usuario.usuarioLogado.getNome_usuario());

        String data = String.valueOf(sdf.format(dataAtual));
        txtData.setText(data);
    }//GEN-LAST:event_formWindowOpened

    private void btnFecharSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharSistemaActionPerformed
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_btnFecharSistemaActionPerformed

    private void buscarServico(int id) {
        try {
            ServicoDTO objServicoDto = new ServicoDTO();
            objServicoDto.setId(id);

            ServicoDAO objServicoDao = new ServicoDAO();
            ResultSet rsServicoDao = objServicoDao.getServico(objServicoDto);

            if (rsServicoDao.next()) {
                objServicoDto.setValor(rsServicoDao.getDouble("preco_item"));
                objServicoDto.setItem(rsServicoDao.getString("nome_item"));

                Boleto objBoleto = new Boleto();
                objBoleto.getServico(objServicoDto);
                objBoleto.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Serviço não encontrado.");
            }

        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "InterfaceALuno: " + erro);
        }
    }
    
    private void permitirRenovacao(){
        try {
            ResultSet rsCarteiraDao = new CarteiraDAO().buscaCarteira(idAlunoLogado);
            
            if(rsCarteiraDao.next()){
                if(rsCarteiraDao.getDate("dt_vencimento").before(dataAtual)){
                    btnRenovacao.setEnabled(true);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
     private void permitirSegundaVia(){
        try {
            ResultSet rsCarteiraDao = new CarteiraDAO().buscaCarteira(idAlunoLogado);    
            if(rsCarteiraDao.next()){
                    btnSegundavia.setEnabled(true);
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmissao;
    private javax.swing.JButton btnFecharSistema;
    private javax.swing.JButton btnRenovacao;
    private javax.swing.JButton btnSegundavia;
    private javax.swing.JLabel txtData;
    private javax.swing.JLabel txtUsuarioLogado;
    // End of variables declaration//GEN-END:variables
}
