package visao.aluno.servicos;

import controle.aluno.AlunoDAO;
import controle.detran.CarteiraDAO;
import controle.detran.ExamesDAO;
import controle.examinador.ExaminadorDAO;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.AlunoDTO;
import modelo.CarteiraDTO;
import visao.aluno.MainAluno;

public class Renovacao extends javax.swing.JFrame {

    AlunoDAO alunoDao = new AlunoDAO();
    boolean aprovado = false;
    Date dataAtual = new Date();

    /**
     * Creates new form InterfaceRenovação
     */
    public Renovacao() {
        initComponents();
        txtOla.setText("Olá, " + AlunoDTO.usuarioLogado.getNome_usuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtOla = new javax.swing.JLabel();
        txtResu = new javax.swing.JLabel();
        btnSolicitar = new javax.swing.JButton();
        btnRealizarExameMedico = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        txtResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        txtOla.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtOla.setText("Olá, #nomeAluno");

        txtResu.setText("Resultado:");

        btnSolicitar.setBackground(new java.awt.Color(0, 0, 0));
        btnSolicitar.setForeground(new java.awt.Color(255, 255, 255));
        btnSolicitar.setText("Imprimir Carteira");
        btnSolicitar.setEnabled(false);
        btnSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarActionPerformed(evt);
            }
        });

        btnRealizarExameMedico.setBackground(new java.awt.Color(51, 102, 255));
        btnRealizarExameMedico.setText("Marcar Exame Médico");
        btnRealizarExameMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarExameMedicoActionPerformed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(255, 51, 51));
        btnClose.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("X");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        txtResultado.setText("x");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtOla)
                            .addComponent(btnRealizarExameMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtResu, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btnSolicitar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClose)
                .addGap(7, 7, 7)
                .addComponent(txtOla)
                .addGap(38, 38, 38)
                .addComponent(btnRealizarExameMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResu)
                    .addComponent(txtResultado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btnSolicitar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRealizarExameMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarExameMedicoActionPerformed
        alunoDao.fazerExame(3);
    }//GEN-LAST:event_btnRealizarExameMedicoActionPerformed

    private void buscarResultadoExame() {
        ResultSet rsExame = new ExamesDAO().buscarExames();

        try {
            while (rsExame.next()) {
                if (rsExame.getInt("tipo_exame_id") == 3) {
                    txtResultado.setText(rsExame.getString("resultado"));

                    if (rsExame.getString("resultado").equals("Aprovado")) {
                        aprovado = true;
                    }
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(Renovacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void habilitarBtnSolicitar() {
        if (aprovado) {
            btnSolicitar.setEnabled(true);
        }
    }

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        habilitarBotaoExame();
        buscarResultadoExame();
        habilitarBtnSolicitar();
    }//GEN-LAST:event_formWindowActivated

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
        new MainAluno().setVisible(true);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarActionPerformed
        CarteiraDTO carteiraDto = new CarteiraDTO();
        
        
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(dataAtual);

        calendar.add(Calendar.YEAR, 4);

        Date dataVencimento = calendar.getTime();
        
        carteiraDto.setAluno_id(AlunoDTO.usuarioLogado.getId_usuario());
        carteiraDto.setDt_emissao(dataAtual);
        carteiraDto.setDt_vencimento(dataVencimento);
        
        new CarteiraDAO().renovarCarteira(carteiraDto);
        
        new Carteira().setVisible(true);
    }//GEN-LAST:event_btnSolicitarActionPerformed

    private void habilitarBotaoExame() {
        ResultSet rsExameALuno = new ExaminadorDAO().buscarExameSendoFeito();

        try {
            if (rsExameALuno.next()) {
                btnRealizarExameMedico.setEnabled(false);
                btnRealizarExameMedico.setText("Aguardando resultado...");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Renovacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Renovacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Renovacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Renovacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Renovacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Renovacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnRealizarExameMedico;
    private javax.swing.JButton btnSolicitar;
    private javax.swing.JLabel txtOla;
    private javax.swing.JLabel txtResu;
    private javax.swing.JLabel txtResultado;
    // End of variables declaration//GEN-END:variables
}
