package visao.examinadores;

import controle.ExaminadorDAO;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ExameDTO;
import modelo.UsuarioDTO;

public class LancarResultadoExame extends javax.swing.JFrame {

    /**
     * Creates new form ResultadoExame
     */
    public LancarResultadoExame() {
        initComponents();
        listarExames();
    }
    
    private void listarExamesEmTabela(int idTipoExame){
        try {
            
            DefaultTableModel modelo = (DefaultTableModel) jTExames.getModel();
            
            ExaminadorDAO examinadorDAO = new ExaminadorDAO();
            
            for(ExameDTO exame : examinadorDAO.listarExamesSemResultado(idTipoExame)){
                modelo.addRow(new Object[]{
                    exame.getId(),
                    exame.getAluno_nome(),
                    exame.getAluno_cpf(),
                    exame.getResultado()
                });
            }
            
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void listarExames(){
        if(UsuarioDTO.usuarioLogado.getPerfil_usuario() == 2){
            listarExamesEmTabela(1);
        }
        
        if(UsuarioDTO.usuarioLogado.getPerfil_usuario() == 4){
            listarExamesEmTabela(2);
        }
        
        if(UsuarioDTO.usuarioLogado.getPerfil_usuario() == 3){
            listarExamesEmTabela(4);
        }
    }
    
    private void lancarResultado(){     
        int rowIndex = jTExames.getSelectedRow();
        if(rowIndex == -1){
            JOptionPane.showMessageDialog(null, "Selecione um exame para lançar o resultado.");
            return;
        }
        
        int idExame = (int) jTExames.getValueAt(rowIndex, 0);
        
        ExameDTO exameDto = new ExameDTO();
        exameDto.setId(idExame);
        
        if(jRApto.isSelected()){
            exameDto.setResultado("Aprovado");
        }
        
        if(jRInapto.isSelected()){
            exameDto.setResultado("Reprovado");
        }
        
        new ExaminadorDAO().editarResultado(exameDto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        optionMedico = new javax.swing.JRadioButton();
        optionPsicologo = new javax.swing.JRadioButton();
        optionMedico1 = new javax.swing.JRadioButton();
        optionPsicologo1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        btnLancar = new javax.swing.JButton();
        jRApto = new javax.swing.JRadioButton();
        jRInapto = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTExames = new javax.swing.JTable();

        optionMedico.setText("Médico");

        optionPsicologo.setText("Psicólogo");

        optionMedico1.setText("Médico");

        optionPsicologo1.setText("Psicólogo");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(614, 470));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Lançar resultado de exame");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(172, 37, 216, 24);

        btnLancar.setBackground(new java.awt.Color(0, 0, 0));
        btnLancar.setForeground(new java.awt.Color(255, 255, 255));
        btnLancar.setText("Lançar");
        btnLancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLancarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLancar);
        btnLancar.setBounds(360, 90, 85, 24);

        buttonGroup1.add(jRApto);
        jRApto.setText("Apto");
        getContentPane().add(jRApto);
        jRApto.setBounds(80, 90, 110, 28);

        buttonGroup1.add(jRInapto);
        jRInapto.setText("Inapto");
        getContentPane().add(jRInapto);
        jRInapto.setBounds(200, 90, 110, 28);

        jTExames.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Aluno", "CPF", "Resutado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTExames);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 130, 570, 290);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLancarActionPerformed
        
        if(jRApto.isSelected() || jRInapto.isSelected()){
            lancarResultado();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione Apto ou Inapto.");
        }
        
    }//GEN-LAST:event_btnLancarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LancarResultadoExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LancarResultadoExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LancarResultadoExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LancarResultadoExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LancarResultadoExame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLancar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRApto;
    private javax.swing.JRadioButton jRInapto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTExames;
    private javax.swing.JRadioButton optionMedico;
    private javax.swing.JRadioButton optionMedico1;
    private javax.swing.JRadioButton optionPsicologo;
    private javax.swing.JRadioButton optionPsicologo1;
    // End of variables declaration//GEN-END:variables
}
