package visao.examinadores;

import modelo.Usuario;
import visao.Login;

public class MainExaminador extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceAgente
     */
    public MainExaminador() {
        initComponents();
        txtUsuarioLogado.setText("Olá, " + Usuario.usuarioLogado.getNome_usuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntTrocarUsuário = new javax.swing.JButton();
        bntTrocarUsuário1 = new javax.swing.JButton();
        bntTrocarUsuário2 = new javax.swing.JButton();
        txtUsuarioLogado = new javax.swing.JLabel();
        btnResultadosLancados = new javax.swing.JButton();
        btnLancarResultado = new javax.swing.JButton();
        btnFecharSistema = new javax.swing.JButton();

        bntTrocarUsuário.setBackground(new java.awt.Color(0, 0, 0));
        bntTrocarUsuário.setForeground(new java.awt.Color(255, 255, 255));
        bntTrocarUsuário.setText("Trocar Usuário");
        bntTrocarUsuário.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntTrocarUsuárioActionPerformed(evt);
            }
        });

        bntTrocarUsuário1.setBackground(new java.awt.Color(0, 0, 0));
        bntTrocarUsuário1.setForeground(new java.awt.Color(255, 255, 255));
        bntTrocarUsuário1.setText("Trocar Usuário");
        bntTrocarUsuário1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntTrocarUsuário1ActionPerformed(evt);
            }
        });

        bntTrocarUsuário2.setBackground(new java.awt.Color(0, 0, 0));
        bntTrocarUsuário2.setForeground(new java.awt.Color(255, 255, 255));
        bntTrocarUsuário2.setText("Trocar Usuário");
        bntTrocarUsuário2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntTrocarUsuário2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtUsuarioLogado.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtUsuarioLogado.setText("Olá, #nomeUsuario");

        btnResultadosLancados.setBackground(new java.awt.Color(0, 0, 0));
        btnResultadosLancados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnResultadosLancados.setForeground(new java.awt.Color(255, 255, 255));
        btnResultadosLancados.setText("Consultar Exames Lançados");
        btnResultadosLancados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadosLancadosActionPerformed(evt);
            }
        });

        btnLancarResultado.setBackground(new java.awt.Color(0, 0, 0));
        btnLancarResultado.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnLancarResultado.setForeground(new java.awt.Color(255, 255, 255));
        btnLancarResultado.setText("Lançar Resultado de Exame");
        btnLancarResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLancarResultadoActionPerformed(evt);
            }
        });

        btnFecharSistema.setBackground(new java.awt.Color(255, 51, 51));
        btnFecharSistema.setForeground(new java.awt.Color(255, 255, 255));
        btnFecharSistema.setText("Sair");
        btnFecharSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharSistemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnLancarResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUsuarioLogado)
                    .addComponent(btnResultadosLancados, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFecharSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(txtUsuarioLogado)
                .addGap(39, 39, 39)
                .addComponent(btnLancarResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnResultadosLancados, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnFecharSistema)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnResultadosLancadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadosLancadosActionPerformed
        new ListaResultadosExame().setVisible(true);
    }//GEN-LAST:event_btnResultadosLancadosActionPerformed

    private void btnLancarResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLancarResultadoActionPerformed
        new LancarResultadoExame().setVisible(true);
    }//GEN-LAST:event_btnLancarResultadoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void bntTrocarUsuárioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntTrocarUsuárioActionPerformed
       
    }//GEN-LAST:event_bntTrocarUsuárioActionPerformed

    private void bntTrocarUsuário1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntTrocarUsuário1ActionPerformed
    
    }//GEN-LAST:event_bntTrocarUsuário1ActionPerformed

    private void bntTrocarUsuário2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntTrocarUsuário2ActionPerformed
        
    }//GEN-LAST:event_bntTrocarUsuário2ActionPerformed

    private void btnFecharSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharSistemaActionPerformed
          new Login().setVisible(true);
          this.dispose();
    }//GEN-LAST:event_btnFecharSistemaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainExaminador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainExaminador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainExaminador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainExaminador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainExaminador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntTrocarUsuário;
    private javax.swing.JButton bntTrocarUsuário1;
    private javax.swing.JButton bntTrocarUsuário2;
    private javax.swing.JButton btnFecharSistema;
    private javax.swing.JButton btnLancarResultado;
    private javax.swing.JButton btnResultadosLancados;
    private javax.swing.JLabel txtUsuarioLogado;
    // End of variables declaration//GEN-END:variables
}
